name: Nostr Crosspost

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

permissions:
  contents: write    # allow committing state updates
  actions: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crossposter
        env:
          RSS_URL: ${{ secrets.RSS_URL }}
          NOSTR_NSEC: ${{ secrets.NOSTR_NSEC }}
          # NOSTR_RELAYS optional; bot.py has sane defaults
          # NOSTR_RELAYS: ${{ secrets.NOSTR_RELAYS }}
          STATE_FILE: state/last_id.txt
          POLL_SECONDS: "0"
        run: |
          python bot.py

      - name: Commit state if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add state/last_id.txt
            git commit -m "Update state"
            git push
          else
            echo "No state changes to commit."
          fi
